# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# frozen_string_literal: true

# stub: tijuana_client 0.2.4 ruby lib

Gem::Specification.new do |s|
  s.name = 'tijuana_client'
  s.version = '0.2.4'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['Nathan Woodhull']
  s.date = '2020-04-29'
  s.description = 'An API client for the code that runs Getup.org.au'
  s.email = 'nathan@controlshiftlabs.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.ruby-gemset',
    '.ruby-version',
    '.travis.yml',
    'Gemfile',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'lib/tijuana_client.rb',
    'lib/tijuana_client/base.rb',
    'lib/tijuana_client/client.rb',
    'lib/tijuana_client/error_middleware.rb',
    'lib/tijuana_client/user.rb',
    'spec/client_spec.rb',
    'spec/spec_helper.rb',
    'spec/tijuana_spec.rb',
    'spec/user_spec.rb',
    'tijuana_client.gemspec'
  ]
  s.homepage = 'http://github.com/controlshift/tijuana_client'
  s.licenses = ['MIT']
  s.rubygems_version = '3.0.4'
  s.summary = 'API client for Tijuana'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('vertebrae', ['> 0.5.0'])
      s.add_development_dependency('bundler', ['>= 0'])
      s.add_development_dependency('jeweler', ['~> 2.1', '>= 2.1.2'])
      s.add_development_dependency('pry', ['>= 0'])
      s.add_development_dependency('pry-byebug', ['>= 0'])
      s.add_development_dependency('rspec', ['>= 0'])
      s.add_development_dependency('webmock', ['>= 0'])
    else
      s.add_dependency('bundler', ['>= 0'])
      s.add_dependency('jeweler', ['~> 2.1', '>= 2.1.2'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('vertebrae', ['> 0.5.0'])
      s.add_dependency('vertebrae', ['> 0.5.0'])
      s.add_dependency('webmock', ['>= 0'])
    end
  else
    s.add_dependency('pry', ['>= 0'])
    s.add_dependency('pry-byebug', ['>= 0'])
    s.add_dependency('vertebrae', ['> 0.5.0'])
    s.add_dependency('vertebrae', ['> 0.5.0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
  end
end
